---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
includeRegExpList:
  - posts/**/*.md
ignorePaths:
  - public
words:
  - Abac
  - appversion
  - Atoi
  - autoprovisioned
  - bitnami
  - bootable
  - changefreq
  - chatbots
  - CLOEXEC
  - clusterrole
  - clusterrolebinding
  - cmdline
  - configmap
  - containerd
  - Contentful
  - cpuset
  - crossplane
  - Crossplane
  - customizeable
  - cxzp
  - daemonset
  - dameon
  - dapr
  - DAPR
  - defaultbackend
  - distroless
  - distrubtion
  - ebpf
  - Ecommerce
  - ENOENT
  - epfd
  - epoll
  - exceiting
  - experince
  - FDCWD
  - flox
  - Gifort
  - giscus
  - gitops
  - godoc
  - Goroutines
  - Groq
  - healthz
  - hostmachine
  - hostnames
  - httputil
  - inclusivity
  - Intelinet
  - Intn
  - kalm
  - lastmod
  - latptop
  - libbpf
  - loggingexporter
  - ltrace
  - Luckly
  - maxevents
  - memberlist
  - messure
  - metallb
  - Metallb
  - mmap
  - myapp
  - myorg
  - myrepository
  - NETGEAR
  - nmap
  - nonroot
  - normallly
  - OLLAMA
  - Ollama
  - ollama
  - openat
  - openweb
  - openzipkin
  - opsnet
  - otelcol
  - pgrep
  - podsecuritypolicy
  - portforward
  - portforwarding
  - println
  - pubsubname
  - raspberrypi
  - raspi
  - RDONLY
  - replicaset
  - rolebinding
  - sandboxed
  - Sandboxed
  - Sandboxing
  - secretkey
  - serviceaccount
  - SPOF
  - ssize
  - strconv
  - subnetworks
  - syscall
  - syscalls
  - terraforming
  - tolerations
  - tracepoints
  - traceree
  - traefik
  - urlset
  - usecs
  - usermod
  - vercel
  - Zipkin
